'use client';
import {useEffect,useState} from 'react';
import {Asterisk,ArrowLeft,Plus,Search,ArrowUpRight,Pencil,Trash2,Link2,LoaderCircle} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import type {Artist,Section} from '@/lib/types';
const blank:Artist={id:'',name:'',url:'',section:'world',platform:'Instagram',description:'',image:'',tags:''};
export default function Admin(){
 const [artists,setArtists]=useState<Artist[]>([]),[sections,setSections]=useState<Section[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[q,setQ]=useState(''),[group,setGroup]=useState('all');
 const [draft,setDraft]=useState<Artist|null>(null),[link,setLink]=useState(''),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[importNote,setImportNote]=useState(''),[newSection,setNewSection]=useState(false),[sectionName,setSectionName]=useState(''),[deleting,setDeleting]=useState<Artist|null>(null);
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/catalog');const d:any=await r.json();if(!r.ok)throw Error(d.error);setArtists(d.artists);setSections(d.sections);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 async function mutate(body:object){const r=await fetch('/api/catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw Error(d.error);return d;}
 function start(a?:Artist){setDraft(a?{...a}:{...blank,section:group==='all'?'world':group});setLink(a?.url||'');setFormError('');setImportNote('');}
 async function importLink(){setBusy(true);setFormError('');setImportNote('');try{const r=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:link})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setDraft(prev=>({...prev!,...d.artist}));setImportNote(d.notice);}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setFormError('');try{const d=await mutate({action:'save',artist:draft});setArtists(prev=>prev.some(a=>a.id===d.artist.id)?prev.map(a=>a.id===d.artist.id?d.artist:a):[d.artist,...prev]);setDraft(null);setNotice('Карточка сохранена и появилась в атласе.');}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
 const filtered=artists.filter(a=>(group==='all'||group===a.section)&&(a.name+' '+a.url+' '+a.tags).toLowerCase().includes(q.toLowerCase()));
 return <><header className="topbar"><a className="brand" href="/"><Asterisk/>иизм<span>КУРАТОРСКАЯ</span></a><a href="/" className="admin-link"><ArrowLeft size={16}/> В атлас</a></header><main className="admin-main"><div className="admin-heading"><div><div className="eyebrow">ВАША КОЛЛЕКЦИЯ</div><h1>Кураторская<span>.</span></h1><p>Находите новых авторов. Дополняйте атлас.</p></div><button className="primary-btn" onClick={()=>start()}><Plus size={18}/> Добавить артиста</button></div><div className="admin-stats"><div><strong>{artists.length}</strong><span>артистов в коллекции</span></div><div><strong>{sections.length}</strong><span>раздела</span></div><button onClick={()=>{setNewSection(true);setFormError('');}}><Plus size={18}/> Новый раздел</button></div>{notice&&<p className="notice" role="status">{notice}</p>}{error&&<div className="error" role="alert">{error} <button onClick={load}>Повторить</button></div>}<div className="admin-tools"><label className="input-search"><Search size={17}/><input aria-label="Поиск артиста" placeholder="Имя, ссылка или тег…" value={q} onChange={e=>setQ(e.target.value)}/></label><Select value={group} onValueChange={setGroup}><SelectTrigger aria-label="Раздел"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Все разделы</SelectItem>{sections.map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select></div><div className="admin-rows">{loading?<p className="empty">Загружаем коллекцию…</p>:filtered.map((a,i)=><div className="admin-row" key={a.id}><span className="row-number">{String(i+1).padStart(3,'0')}</span><div className={'mini-art art-'+i%8}><Asterisk size={26}/></div><div className="row-name"><strong>{a.name}</strong><a href={a.url} target="_blank" rel="noreferrer">{a.platform} <ArrowUpRight size={12}/></a></div><span className="section-chip">{sections.find(s=>s.id===a.section)?.name}</span><button aria-label={'Редактировать '+a.name} onClick={()=>start(a)}><Pencil size={17}/></button><button aria-label={'Удалить '+a.name} onClick={()=>setDeleting(a)}><Trash2 size={17}/></button></div>)}{!loading&&!filtered.length&&!error&&<p className="empty">Нет артистов по этому запросу.</p>}</div></main>
 <Dialog open={!!draft} onOpenChange={open=>{if(!open&&!busy)setDraft(null);}}><DialogContent className="editor-dialog"><DialogTitle>{draft?.id?'Редактировать артиста':'Новый артист'}</DialogTitle><DialogDescription>Вставьте ссылку на Instagram или Telegram — начнём с неё.</DialogDescription><div className="import-box"><label htmlFor="import-link"><Link2 size={15}/> Ссылка на профиль или пост</label><div><input id="import-link" type="url" value={link} placeholder="https://www.instagram.com/…" onChange={e=>{setLink(e.target.value);if(!draft?.id)setDraft(prev=>({...prev!,url:e.target.value}));}} disabled={busy}/><button type="button" className="primary-btn" onClick={importLink} disabled={busy||!link.trim()}>{busy?<LoaderCircle className="spin" size={18}/>:'Заполнить'}</button></div></div>{importNote&&<p className="notice" role="status">{importNote}</p>}{draft&&<form onSubmit={save} className="artist-form"><div className="form-pair"><label>Имя артиста<input required maxLength={120} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Раздел<Select value={draft.section} onValueChange={section=>setDraft({...draft,section})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{sections.map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select></label></div><label>Ссылка карточки<input required type="url" value={draft.url} onChange={e=>setDraft({...draft,url:e.target.value})}/></label><label>Описание<textarea rows={3} maxLength={1500} placeholder="Что вы хотите рассказать об авторе?" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Обложка <span className="optional">· ссылка на изображение, необязательно</span><input type="url" placeholder="https://…" value={draft.image} onChange={e=>setDraft({...draft,image:e.target.value})}/></label><label>Теги <span className="optional">· через запятую</span><input maxLength={250} placeholder="Сюрреализм, видеоарт…" value={draft.tags} onChange={e=>setDraft({...draft,tags:e.target.value})}/></label>{formError&&<p className="error" role="alert">{formError}</p>}<div className="form-actions"><button className="secondary-btn" type="button" disabled={busy} onClick={()=>setDraft(null)}>Отмена</button><button className="primary-btn" disabled={busy} type="submit">{busy?'Подождите…':'Сохранить карточку'} <ArrowUpRight size={17}/></button></div></form>}</DialogContent></Dialog>
 <Dialog open={newSection} onOpenChange={open=>{if(!busy)setNewSection(open);}}><DialogContent className="editor-dialog"><DialogTitle>Новый раздел</DialogTitle><DialogDescription>Раздел появится в атласе и в списке при добавлении артиста.</DialogDescription><form className="artist-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setFormError('');try{const d=await mutate({action:'section',name:sectionName});setSections(p=>[...p,d.section]);setSectionName('');setNewSection(false);setNotice('Раздел создан. Теперь можно добавить в него артистов.');}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}}><label>Название<input required maxLength={60} value={sectionName} onChange={e=>setSectionName(e.target.value)}/></label>{formError&&<p className="error">{formError}</p>}<button className="primary-btn" disabled={busy}>Создать раздел</button></form></DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={open=>{if(!open&&!busy)setDeleting(null);}}><AlertDialogContent className="editor-dialog"><AlertDialogHeader><AlertDialogTitle>Удалить {deleting?.name}?</AlertDialogTitle><AlertDialogDescription>Карточка исчезнет из каталога. При необходимости её можно добавить снова по ссылке.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Отмена</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();setBusy(true);try{await mutate({action:'delete',id:deleting?.id});setArtists(p=>p.filter(a=>a.id!==deleting?.id));setDeleting(null);setNotice('Карточка удалена.');}catch(e){setError((e as Error).message);setDeleting(null);}finally{setBusy(false);}}}>Удалить</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
