'use client';
import {useState,useRef} from 'react';
import {Plus,Minus,RotateCcw} from 'lucide-react';
import type {Artist,Section} from '@/lib/types';
export default function ArtistMap({artists,sections,onSelect}:{artists:Artist[];sections:Section[];onSelect:(a:Artist)=>void}){
 const [zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0});const drag=useRef<{x:number;y:number;px:number;py:number}|null>(null);const moved=useRef(false);
 const groups=sections.filter(s=>artists.some(a=>a.section===s.id));
 const nodes=groups.flatMap((s,g)=>{const members=artists.filter(a=>a.section===s.id);const cx=groups.length===1?600:300+g%2*600,cy=310+Math.floor(g/2)*560;return members.map((a,i)=>{const angle=i*2.39996;const r=42+Math.sqrt(i)*25;return {a,x:cx+Math.cos(angle)*r,y:cy+Math.sin(angle)*r,cx,cy};});});
 const height=Math.max(620,Math.ceil(groups.length/2)*560+60);
 return <div className="map-wrap"><div className="map-note"><span><i/> МИР</span><span><i/> РУНЕТ И ДРУГИЕ</span><p>Перетаскивайте карту · выберите автора</p></div><svg role="group" aria-label="Карта артистов по разделам" viewBox={`0 0 1200 ${height}`} onPointerDown={e=>{if((e.target as Element).closest('[data-node]'))return;moved.current=false;drag.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current)return;const k=1200/e.currentTarget.getBoundingClientRect().width;moved.current=true;setPan({x:drag.current.px+(e.clientX-drag.current.x)*k,y:drag.current.py+(e.clientY-drag.current.y)*k});}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null} style={{touchAction:'none'}}><defs><pattern id="dots" width="25" height="25" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".7" fill="#37402e"/></pattern></defs><rect width="1200" height={height} fill="url(#dots)"/><g transform={`translate(${600+pan.x} ${height/2+pan.y}) scale(${zoom}) translate(-600 ${-height/2})`}>{nodes.map(({a,x,y,cx,cy})=><line key={'line'+a.id} x1={cx} y1={cy} x2={x} y2={y} stroke={a.section==='world'?'#8dba5533':'#a18abe33'}/>)}{groups.map((s,g)=><g key={s.id}><circle cx={groups.length===1?600:300+g%2*600} cy={310+Math.floor(g/2)*560} r="30" fill="#17200f" stroke="#93b866"/><text x={groups.length===1?600:300+g%2*600} y={315+Math.floor(g/2)*560} textAnchor="middle" fill="#d5e8bc" fontSize="14">{s.name.slice(0,18)}</text></g>)}{nodes.map(({a,x,y},i)=><g data-node="true" className="map-node" key={a.id} role="button" tabIndex={0} aria-label={a.name} onClick={()=>onSelect(a)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(a);}}}><circle cx={x} cy={y} r="16" fill="transparent"/><circle cx={x} cy={y} r={i%7===0?7:4} fill={a.section==='world'?'#c9e999':'#bca4d5'}/><text x={x+11} y={y+4} fill="#cbd3bf" fontSize="11">{a.name}</text></g>)}</g></svg><div className="map-controls"><button aria-label="Приблизить" onClick={()=>setZoom(z=>Math.min(3,z+.25))}><Plus size={18}/></button><span>{Math.round(zoom*100)}%</span><button aria-label="Отдалить" onClick={()=>setZoom(z=>Math.max(.5,z-.25))}><Minus size={18}/></button><button aria-label="Сбросить карту" onClick={()=>{setZoom(1);setPan({x:0,y:0});}}><RotateCcw size={16}/></button></div><p className="map-caption">Связи обозначают разделы каталога</p></div>;
}
