import {useEffect,useState} from 'react';
import {Plus,ArrowUpRight,Play,Pencil,Trash2,Search} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {catalogUrl,adminUrl,showLocalAdmin} from '@/client/config';
import type {Video} from '@/lib/types';
const blank:Video={id:'',name:'',url:'',platform:'',videoId:'',reference:false,title:'',publishedAt:'',dateSource:'unknown',dateUrl:'',image:'',description:'',alternateUrls:[],sourceOrder:0};
export default function Videos({admin=false}:{admin?:boolean}){
 const [videos,setVideos]=useState<Video[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[order,setOrder]=useState('source'),[platform,setPlatform]=useState('all'),[draft,setDraft]=useState<Video|null>(null),[selected,setSelected]=useState<Video|null>(null),[deleting,setDeleting]=useState<Video|null>(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState('');
 async function load(){try{setError('');const r=await fetch(catalogUrl,{cache:'no-store'});if(!r.ok)throw Error('Не удалось загрузить видео.');const items=(await r.json()).videos||[];setVideos(items);if(admin){const editId=new URLSearchParams(location.search).get("edit");if(editId){const item=items.find((v:Video)=>v.id===editId);if(item)edit(item);const url=new URL(location.href);url.searchParams.delete("edit");history.replaceState(null,"",url);}}}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 async function mutate(body:object){const r=await fetch('/api/catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
 const filtered=videos.filter(v=>(platform==='all'||v.platform===platform)&&(v.name+' '+v.title).toLowerCase().includes(q.toLowerCase()));
 const originalOrder=[...filtered].sort((a,b)=>a.sourceOrder-b.sourceOrder);
 const dated=filtered.filter(v=>v.publishedAt).sort((a,b)=>a.publishedAt.localeCompare(b.publishedAt)||a.sourceOrder-b.sourceOrder);
 const undated=filtered.filter(v=>!v.publishedAt).sort((a,b)=>a.sourceOrder-b.sourceOrder);
 const years=[...new Set(dated.map(v=>v.publishedAt.slice(0,4)))];
 function edit(v?:Video){setDraft(v?{...v}:{...blank});setFormError('');}
 function card(v:Video){return <article className="video-card" key={v.id}><div className="video-date">{order==='source'&&<span className="source-number">№ {v.sourceOrder+1}</span>}<time dateTime={v.publishedAt||undefined}>{v.publishedAt?new Date(v.publishedAt+'T12:00:00').toLocaleDateString('ru-RU',{day:'2-digit',month:'short',...(order==='source'?{year:'numeric' as const}:{})}):'—'}</time><small>{!v.publishedAt?'Дата неизвестна':v.dateSource==='manual'?'Указана куратором':v.platform==='Telegram'?'Дата поста':'Дата публикации'}</small></div><button className="video-thumb" aria-label={'Открыть видео '+v.name} onClick={()=>setSelected(v)}><span className="video-placeholder"><Play size={24}/></span>{v.image&&<img src={v.image} alt="" loading="lazy" referrerPolicy="no-referrer" onError={e=>e.currentTarget.style.display='none'}/>}<span className="video-play"><Play size={18}/></span></button><div className="video-copy"><span className="video-platform">{v.platform}{v.reference?' · ссылка на источник':''}</span><h3><button onClick={()=>setSelected(v)}>{v.name}</button></h3>{v.title&&v.title!==v.name&&<p>{v.title}</p>}<a href={v.url} target="_blank" rel="noreferrer">Открыть источник <ArrowUpRight size={14}/></a></div>{!admin&&showLocalAdmin&&<a className="card-edit" href={adminUrl+"/?edit="+encodeURIComponent(v.id)+"#videos"} aria-label={"Редактировать видео "+v.name}>edit</a>}{admin&&<div className="video-actions"><button aria-label={'Редактировать видео '+v.name} onClick={()=>edit(v)}><Pencil size={17}/></button><button aria-label={'Удалить видео '+v.name} onClick={()=>setDeleting(v)}><Trash2 size={17}/></button></div>}</article>;}
 return <section className="video-section"><div className="video-heading"><div><div className="eyebrow">ВИДЕОАРХИВ</div><h1>Хронология видео<span>.</span></h1><p>Ваш порядок ссылок или хронология по найденным датам публикаций и постов.</p></div>{admin&&<button className="primary-btn" onClick={()=>edit()}><Plus size={18}/>Добавить видео</button>}</div><div className="video-toolbar"><label className="input-search"><Search size={17}/><input aria-label="Поиск видео" placeholder="Автор или название видео…" value={q} onChange={e=>setQ(e.target.value)}/></label><div><Select value={platform} onValueChange={setPlatform}><SelectTrigger aria-label="Площадка видео"><SelectValue/></SelectTrigger><SelectContent>{['all','YouTube','Telegram','Instagram','VK','Сайт'].map(p=><SelectItem key={p} value={p}>{p==='all'?'Все площадки':p}</SelectItem>)}</SelectContent></Select><Select value={order} onValueChange={setOrder}><SelectTrigger aria-label="Порядок видео"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="source">Как в исходном списке</SelectItem><SelectItem value="dates">По найденным датам</SelectItem></SelectContent></Select></div></div><div className="video-summary">{filtered.length} записей · {dated.length} с датой · {undated.length} без даты</div>{error&&<p role="alert" className="error">{error} <button onClick={load}>Повторить</button></p>}{loading?<p className="empty">Загружаем видео…</p>:<div className={`timeline-layout${order==='source'?' timeline-layout--source':''}`}>{order!=='source'&&<nav className="timeline-years" aria-label="Годы таймлайна">{years.map(y=><a key={y} href={'#year-'+y}>{y}</a>)}{undated.length>0&&<a href="#year-unknown">Без даты <small>{undated.length}</small></a>}</nav>}<div className="timeline-content">{order==='source'?<section className="timeline-year"><h2>Исходный порядок<sup>{originalOrder.length}</sup></h2><p className="undated-note">Все записи на своих местах, независимо от наличия даты.</p>{originalOrder.map(card)}</section>:<>{years.map(y=><section id={'year-'+y} className="timeline-year" key={y}><h2>{y}<sup>{dated.filter(v=>v.publishedAt.startsWith(y)).length}</sup></h2>{dated.filter(v=>v.publishedAt.startsWith(y)).map(card)}</section>)}{undated.length>0&&<section id="year-unknown" className="timeline-year"><h2>Дата неизвестна<sup>{undated.length}</sup></h2><p className="undated-note">Ссылки сохранены в порядке вашего списка. Дату можно указать в админке.</p>{undated.map(card)}</section>}</>}{!filtered.length&&<p className="empty">По этому запросу видео не найдены.</p>}</div></div>}
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="editor-dialog video-dialog"><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>{selected?.title||selected?.platform}</DialogDescription>{selected?.videoId?<iframe title={selected.name} src={'https://www.youtube-nocookie.com/embed/'+selected.videoId} allow="encrypted-media; picture-in-picture; fullscreen" allowFullScreen/>:<p>Посмотреть видео можно на странице источника.</p>}{selected?.reference&&<p className="notice">В исходном списке указан профиль или сайт, а не конкретная видеопубликация.</p>}<a className="primary-btn" href={selected?.url} target="_blank" rel="noreferrer">Открыть {selected?.platform}<ArrowUpRight size={17}/></a>{selected?.alternateUrls.map((url,i)=><a key={url} href={url} target="_blank" rel="noreferrer">Альтернативный источник {i+1} ↗</a>)}{selected?.description&&<p>{selected.description}</p>}</DialogContent></Dialog>
 <Dialog open={!!draft} onOpenChange={open=>{if(!open&&!busy)setDraft(null);}}><DialogContent className="editor-dialog"><DialogTitle>{draft?.id?'Редактировать видео':'Новое видео'}</DialogTitle><DialogDescription>Дата определяет положение на таймлайне. Если она неизвестна, оставьте поле пустым.</DialogDescription>{draft&&<form className="artist-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setFormError('');try{await mutate({action:'video-save',video:draft});setDraft(null);await load();}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}}><label>Ссылка на видео<input required type="url" value={draft.url} onChange={e=>setDraft({...draft,url:e.target.value,publishedAt:'',dateSource:'unknown',dateUrl:'',videoId:'',image:'',title:''})}/></label><button type="button" disabled={busy||!draft.url} className="secondary-btn" onClick={async()=>{setBusy(true);setFormError('');try{const r=await fetch('/api/video-import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:draft.url})});const d=await r.json();if(!r.ok)throw Error(d.error);setDraft(v=>({...v!,...d,name:v!.name||d.title||''}));if(!d.publishedAt)setFormError('Дата не найдена. Её можно указать вручную или сохранить видео без даты.');}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}}>Получить название и дату</button><label>Автор / название<input required maxLength={160} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Дата публикации<input type="date" value={draft.publishedAt} onChange={e=>setDraft({...draft,publishedAt:e.target.value,dateSource:'manual',dateUrl:''})}/></label><label>Описание<textarea value={draft.description} maxLength={1500} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>{formError&&<p className="notice" role="status">{formError}</p>}<div className="form-actions"><button type="button" className="secondary-btn" onClick={()=>setDraft(null)} disabled={busy}>Отмена</button><button className="primary-btn" disabled={busy}>Сохранить видео</button></div></form>}</DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={open=>{if(!open&&!busy)setDeleting(null);}}><AlertDialogContent className="editor-dialog"><AlertDialogTitle>Удалить видео {deleting?.name}?</AlertDialogTitle><AlertDialogDescription>Запись исчезнет из видеоархива.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>Отмена</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();setBusy(true);try{await mutate({action:'video-delete',id:deleting?.id});setDeleting(null);await load();}catch(e){setError((e as Error).message);setDeleting(null);}finally{setBusy(false);}}}>Удалить</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>;
}
